### ISSUE TITLE
[Bug] Fix the spelling for the word "Percentage"

### ISSUE THREAD

**Issue by johnbusty** [Soorya666/TNP-SPELLCHECK#1]
![image](https://github.com/Soorya666/TNP-SPELLCHECK/assets/142680284/1b9a1f54-f1aa-4650-b566-b306de241711)

**Comment by johnbusty** [comment]
hey @Soorya666 assign this issue to me

**Comment by Soorya666** [comment]
ok sounds good @johnbusty #1
